app: DB-GPT
repo: https://github.com/fangyinc/DB-GPT
commit: f317740d5557b56899d1a3e786ca7cc583fdd700
defect_id: fangyinc-DB-GPT-missing_llm_input_format_validation-case3
type: Missing LLM input format validation
case: '3'
consequence:
- ST
- IC
locations:
- dbgpt/app/scene/chat_normal/chat.py/generate_input_values
trigger_tests:
- '1.Create a new chat knowledge with ppt

  2.Upload and wait for Synch

  3.Chat with this new space

  4.Error occured unexpectedly. when chat via web console，exception raised:

    File "d:\code\db-gpt\pilot\openapi\api_v1\api_v1.py", line 449, in stream_generator

      async for chunk in chat.stream_call():

    File "d:\code\db-gpt\pilot\scene\chat_knowledge\v1\chat.py", line 61, in stream_call

      input_values = self.generate_input_values()

    File "d:\code\db-gpt\pilot\scene\chat_knowledge\v1\chat.py", line 95, in generate_input_values

      set([os.path.basename(d.metadata.get("source", "")) for d in docs])

    File "d:\code\db-gpt\pilot\scene\chat_knowledge\v1\chat.py", line 95, in <listcomp>

      set([os.path.basename(d.metadata.get("source", "")) for d in docs])

    File "C:\Users\Peter\miniconda3\envs\dbgpt_env\lib\ntpath.py", line 242, in basename

      return split(p)[1]

    File "C:\Users\Peter\miniconda3\envs\dbgpt_env\lib\ntpath.py", line 211, in split

      p = os.fspath(p)

  TypeError: expected str, bytes or os.PathLike object, not int


  And returned error is:

  Sorry, We meet some error, please try agin later.'
